name: Tests report

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  report:
    permissions:
      contents: read
      actions: read
      checks: write
    uses: zs-dima/lints_tool/.github/workflows/test-report.yml@v1
